test1:
	python sha256.py < test1.in > output && diff output test1.out

test2:
	python sha256.py < test2.in > output && diff output test2.out

test3:
	python sha256.py < test3.in > output && diff output test3.out

test4:
	python sha256.py < test4.in > output && diff output test4.out

test5:
	python sha256.py < test5.in > output && diff output test5.out